#!/usr/bin/env python3
"""Gzip web assets into PROGMEM header (SPEC 68, 88)."""
import argparse
import gzip
import pathlib
import sys

ASSETS = {"index.html": "text/html", "setup.html": "text/html", "locations.json": "application/json"}
ROOT = pathlib.Path(__file__).resolve().parents[1]


def render() -> str:
    out = ["#pragma once",
           "// GENERATED by tools/build_web.py - do not edit. Gzipped web assets.",
           "#include <pgmspace.h>", ""]
    for name, mime in ASSETS.items():
        raw = (ROOT / "web" / name).read_bytes()
        gz = gzip.compress(raw, 9, mtime=0)
        ident = name.replace(".", "_").replace("-", "_").upper()
        body = ",".join(str(b) for b in gz)
        out += [f"// {name}: {len(raw)} -> {len(gz)} bytes",
                f"static const uint8_t ASSET_{ident}[] PROGMEM = {{{body}}};",
                f"static const size_t ASSET_{ident}_LEN = {len(gz)};",
                f"static const char ASSET_{ident}_MIME[] = \"{mime}\";", ""]
        print(f"{name}: {len(raw)} -> {len(gz)} bytes gzip")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if WebAssets.h is not up to date")
    args = parser.parse_args()
    target = ROOT / "src/web/WebAssets.h"
    content = render()
    if args.check:
        if not target.exists() or target.read_text() != content:
            print("src/web/WebAssets.h is stale; run tools/build_web.py", file=sys.stderr)
            return 1
        print("src/web/WebAssets.h is up to date")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    print("-> src/web/WebAssets.h")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
