#!/usr/bin/env python3
"""Gzip web assets into PROGMEM header (SPEC 68, 88). Run after editing web/."""
import gzip
import pathlib

ASSETS = {"index.html": "text/html", "locations.json": "application/json"}
out = ["#pragma once",
       "// GENERATED by tools/build_web.py - do not edit. Gzipped web assets.",
       "#include <pgmspace.h>", ""]
for name, mime in ASSETS.items():
    raw = pathlib.Path("web", name).read_bytes()
    gz = gzip.compress(raw, 9, mtime=0)
    ident = name.replace(".", "_").replace("-", "_").upper()
    body = ",".join(str(b) for b in gz)
    out += [f"// {name}: {len(raw)} -> {len(gz)} bytes",
            f"static const uint8_t ASSET_{ident}[] PROGMEM = {{{body}}};",
            f"static const size_t ASSET_{ident}_LEN = {len(gz)};",
            f"static const char ASSET_{ident}_MIME[] = \"{mime}\";", ""]
    print(f"{name}: {len(raw)} -> {len(gz)} bytes gzip")
pathlib.Path("src/web").mkdir(parents=True, exist_ok=True)
pathlib.Path("src/web/WebAssets.h").write_text("\n".join(out))
print("-> src/web/WebAssets.h")
