#!/usr/bin/env python3
"""Location catalogue generator (SPEC 13-14).

Source: the official UID table shipped in alerts-ua/alerts-in-ua-py
(location_uid_resolver.py). It contains oblasts, raions and the two
special-status cities. Hromada UIDs are NOT published officially - hromada
selection is a documented v1 limitation (docs/RESEARCH.md).

Hierarchy is recovered from table order: each oblast is followed by its raions.

Outputs:
  web/locations.json      - browser catalogue (names, for the Locations UI)
  src/alerts/LocationTable.h - PROGMEM matching table for firmware
"""
import ast
import json
import re
import sys
import urllib.request
from datetime import datetime, timezone

SRC = ("https://raw.githubusercontent.com/alerts-ua/alerts-in-ua-py/"
       "master/alerts_in_ua/location_uid_resolver.py")

def fetch_table() -> dict[int, str]:
    with urllib.request.urlopen(SRC, timeout=30) as r:
        text = r.read().decode()
    m = re.search(r"self\.uid_to_location\s*=\s*(\{.*?\})", text, re.S)
    if not m:
        sys.exit("uid_to_location dict not found in source")
    return ast.literal_eval(m.group(1))

def classify(name: str) -> str:
    if name.startswith("м. "):
        return "city"
    if name.endswith("область"):
        return "oblast"
    if name.endswith("район"):
        return "raion"
    if "Автономна Республіка" in name:
        return "oblast"  # АР Крим behaves as an oblast-level unit
    return "unknown"

def main() -> None:
    table = fetch_table()
    locations, cur_oblast = [], 0
    for uid, name in table.items():  # insertion order = official order
        typ = classify(name)
        loc = {"uid": uid, "name": name, "type": typ}
        if typ in ("oblast",):
            cur_oblast = uid
        elif typ == "raion":
            loc["oblast_uid"] = cur_oblast
        locations.append(loc)

    # validation (SPEC 144)
    uids = [l["uid"] for l in locations]
    assert len(uids) == len(set(uids)), "duplicate UID"
    assert all(l["name"] for l in locations), "empty name"
    assert all(l["type"] != "unknown" or l["uid"] in (0,) for l in locations), \
        f"unclassified: {[l for l in locations if l['type'] == 'unknown']}"
    for l in locations:
        if "oblast_uid" in l:
            assert l["oblast_uid"] in uids, f"bad parent for {l}"

    out = {
        "schema": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "alerts.in.ua official UID table (alerts-in-ua-py)",
        "count": len(locations),
        "locations": locations,
    }
    with open("web/locations.json", "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, separators=(",", ":"))

    type_enum = {"oblast": 0, "raion": 1, "hromada": 2, "city": 3, "unknown": 4}
    rows = "\n".join(
        f"    {{{l['uid']}, {type_enum[l['type']]}, {l.get('oblast_uid', 0)}, 0}},"
        for l in sorted(locations, key=lambda x: x["uid"]))
    with open("src/alerts/LocationTable.h", "w", encoding="utf-8") as f:
        f.write(f"""#pragma once
// GENERATED by tools/update_locations.py - do not edit (SPEC 13-14).
// {len(locations)} locations, source: official alerts.in.ua UID table.
#include <cstdint>

struct LocationRow {{
    uint16_t uid;
    uint8_t type;       // LocationType enum order
    uint16_t oblastUid; // 0 = none
    uint16_t raionUid;  // 0 = none (hromada UIDs not published officially)
}};

constexpr LocationRow kLocationTable[] = {{
{rows}
}};
constexpr size_t kLocationTableSize = sizeof(kLocationTable) / sizeof(kLocationTable[0]);
""")
    print(f"ok: {len(locations)} locations -> web/locations.json, src/alerts/LocationTable.h")

if __name__ == "__main__":
    main()
